
version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - AZURE_CONTAINER_NAME=rag-documents
      - ALLOWED_ORIGINS=https://your-frontend-domain.azurecontainerapps.io,http://localhost:3000
    ports:
      - "8000:8000"
    volumes:
      - ../storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=https://your-backend-domain.azurecontainerapps.io/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
